numberscope/backscope

README.md
TODO.md
flaskr/nscope/models.py
flaskr/nscope/views.py

Specifically, api/get_oeis_name_and_values/<OEIS_ID> is guaranteed
to give the correct official OEIS name of the sequence, and
api/get_oeis_metadata/<OEIS_ID> which returns the official name,
cross references, and beack references to the sequence.
Documents these in the README (as there isn't really any other documentation
place at the moment).
Also removes the obsolete TODO.md (it only had one item, which is done, and
we mostly rely on GitHub issues for todos now anyway).
Resolves #17.
Basically, this is just a version of #26 compatible with the new resolve to only store data in the database, and that PR should be closed once this is merged.

feat: Add endpoints for sequence metadata

---

README.md
flaskr/nscope/models.py
flaskr/nscope/views.py
requirements.txt

This implements factoring on the backend using pari via cypari2.  Adds an endpoint that returns the requested number of factorizations.  The browser has to wait, and there's a limit on the size of integers it will be willing to factor (returning "None" as the factorization of terms which are too big).
This PR adds a column to the table ```sequences``` called ```factors```.  It contains an array the same size/indices as the array of values.  The entries are strings representing arrays, which are in the same format that pari creates when factoring.  This was chosen because mathematicians familiar with pari will be used to this and pari put some effort into the design.  For example, you can recreate the term by easily looping through the factors and multiplying, even with 1 and 0.  
Also, I …

add factoring endpoint to backend

---

flaskr/nscope/views.py
server/README.md
server/add-numberscope-service.sh
server/create-symlinks.sh

This PR:
- Fixes the `get_valid_oeis_id` function. When you tried to set `valid_id[0] = first_character.upper()`, you'd get `TypeError: 'str' object does not support item assignment`.
- Fixes a typo in a shell script.
- Adds a shell script that you can run to add the `numberscope` systemd service.
- Adds some comments, and a note to the `server/README.md` file.

fix/docs: fix `get_valid_oeis_id`, fix shell script, add shell script, add some docs

---

README.md
doc/api_endpoints.md
doc/directory_descriptions.md
doc/resetting-the-database.md

This PR:
- updates/improves the README
- removes any OS or distribution-specific instructions about Postgres (we're keeping it deliberately vague so that the user has to figure out their specific setup rather than just copying and pasting commands from the README, which might lead to issues with their setup)
- moves some of the info that was in the README into docs in the doc dir

docs: update README, move some docs to doc dir

---

flaskr/nscope/models.py
flaskr/nscope/views.py

Decouples the fetching of metadata from values and factoring, and
allows each of these steps to occur sequentially or asynchronously
(except factoring has to occur after values). Adds booleans to the
database scheme to keep track of whether the value-fetching or
metadata-fetching steps have been initiated, thereby avoiding
race conditions
Resolves #66.
NOTE: This PR modifies the database schema! Therefore to test it, it is necessary to delete and reinitialize your database. The directions for doing so are in `doc/resetting-the-database.md`.

fix: Avoid race conditions with multiple requests for same sequence

---

doc/update-backscope.md
doc/update-frontscope.md

While updating the server, I noticed there were no instructions on how to update frontscope. It's pretty easy, but there should be documentation for people who aren't familiar with how the server is configured.

docs: add doc on updating frontscope

---

README.md
requirements-freeze.txt
tools/install-requirements.sh

As hoped, this upgrade significantly simplifies the install-requirements.sh
script. Provides additional progress on #43.
Note this must be tested with care (additional details in PR).
Resolves #82.
NOTE the additional testing details: To properly test this PR, you must blow away your entire .venv virtual environment, and reset your database. Then re-do the installation from the step of creating the virtual environment. When `flask run` succeeds and you have successfully hit the resulting server getting back sensible data, then you can run `flask test`. When all of that is good, and if the source changes look OK under review, then this PR can be approved to merge.

chore: Update to Cython3

---

doc/resetting-the-database.md
flaskr/__init__.py
flaskr/config.py
flaskr/nscope/test/abstract_endpoint_test.py

Document the command that clears the database. It's been renamed `clear-database`, since the old name (`init-db`) was confusing.
- The instructions for resetting the database are a lot wordier now. Is it too much?
- The clear-database command asks for confirmation if Backscope is running in production mode. To support this, I've added a `PRODUCTION` flag to the app config.
- In the instructions for wiping out the database structure, I've removed the suggestion to use `rm -rf` to get rid of the migrations folder. In my opinion, someone who should do that won't need the suggestion, and someone who needs the suggestion shouldn't do it.

Rename and document clear-database command

---

flaskr/nscope/test/abstract_endpoint_test.py
flaskr/nscope/test/test_get_commit.py
flaskr/nscope/test/test_get_oeis_values.py
flaskr/nscope/test/test_lookup_errors.py

Add a test to make sure that `get_oeis_values` gives the expected error response when you ask for a sequence that's not in the OEIS, rather than hanging or crashing.
Right now, the error response is text rather than JSON, so I extended `AbstractEndpointTest` to accommodate this. The parameter `expected_response_json` has been replaced with `expected_response`, which must be a dictionary or a string. If it's a dictionary, it's compared against `response.json`. If it's a string, it's compared against `response.text`.
I think tests for the other lookup errors will have to wait for the mock OEIS, because they can't be triggered at will.
To streamline error handling in the front end, maybe we should make the error signal more convenient to detect. For example, we could use HTTP status codes to …

Test `get_oeis_values` response for nonexistent sequence

---

doc/server-administration.md

When I went to install the latest version of the software on the production server, I realized there were not explicit steps for doing so recorded in the documentation. This PR begins to fill that gap, with the knowledge I have gleaned so far.

doc: Record the steps used to update server software

---

flaskr/__init__.py
flaskr/nscope/views.py
server/production.sh

This way, the server continues to supply the correct git revision hash
even if the code changes after startup. Unless overridden by an
environment variable, simply uses `git rev-parse --short HEAD`. In
production, uses the environment override because the eventual flask
process doesn't have the correct permissions to perform the git
command.
Resolves #108.

fix: Determine git revision hash once at startup

---

server/production.sh

#113 as merged caused the backscope in production to crash, as it was trying to get the git revision of the backscope software from the wrong userid. This PR represents precisely the hot fix **currently installed in production** under which it appears to be running fine. So merging this (which @katestange  please take a look and do as soon as convenient, since @Vectornaut is swamped) will simply bring the repo to match what is currently running in production.

fix: Hot fix for #113 in production

---

wsgi.py

This causes the output for any test failures to show full diffs, however
large they may be (only when the -v flag is specified).
Resolves #116.

feat: `flask test -v` sets maxDiff to None

---

server/production.sh

The python package gunicorn is only needed in production (but it is required in that setting). Hence there is nothing in requirements.txt etc that installs it. This means that when .venv is blown away (such as migrating to a new server, recovering from a failure, or simply testing full installation or cleaning out an old .venv that has accumulated unneeded code), production fails unless gunicorn is installed. (And indeed, that is exactly what happened when #109 was installed in production.) This PR adds a line to server/production.sh to install gunicorn, and precisely reflects the hot fix that is already present and running in production to cope with the situation.
In other words, merging this and installing in production will result in no change to current production, and should prevent …

fix: Production hot fix to install gunicorn

---

flaskr/nscope/test/test_get_oeis_values.py
flaskr/nscope/views.py

Store the shift of a squence in the database, and parse both negative
and positive indices of entries.
Unskip the positive offset test and add a test for a sequence with
a negative offset (and fewer terms than is requested, to make sure
that works as well).
Resolves #77.
Resolves #50.

fix: Support nonzero sequence shifts (positive and negative)

---

README.md
doc/install-ubuntu.md
requirements-freeze.txt

This will reconcile development and production versions, while maintaining the ability to develop on Ubuntu 20.04.

chore: Bump cypari2 to 2.1.5 and document new Python requirements

---

doc/server-administration.md

I have run exactly the steps added in server-administration.md on the
production machine (they were recorded contemporaneously as I was doing
them). Production is now serving the offset-test sequences with the
correct offsets.

doc: Record the steps used to reset the server database

---

flaskr/nscope/test/test_wrong_response_type.py
flaskr/nscope/views.py

[This is simply a single-commit version of #135.]
Corrects the search query in get_oeis_name_and_values. The Requests
library automatically URL-encodes the query, so the : in the query
gets sent as %3A.
Resolves #133.

fix: Update format for search by ID

---

doc/server-administration.md
flaskr/nscope/views.py

It appears in production that cypari is crashing, but the backtrace
is pretty uninformative. And there is not currently a known way to
reproduce the error when running locally. So this commit wraps the
factoring call to cypari in a try-except and then attempts to log
the result. It is unclear whether this works, because I am unsure of any
soecific way to trigger the exception. So if it is not doing any harm,
perhaps we can put this in production, and then see what we get in the log
from factoring attempts.
It also improves some of the advice/pointers for finding log information
on the server.

fix: Attempt to catch cypari factoring errors

---

flaskr/nscope/views.py

Even with #145, production is still producing a 502 Bad Gateway on https://numberscope.colorado.edu/api/get_oeis_factors/A000045/128, so this PR moves the cypari call that is now erroring into the try-catch block in the hopes that we can at least get a sensible (if incomplete) response for factor requests, to allow moving forward with frontscope. As with #145, this merely allows the server to respond in the face of #143, not really dealing with the underlying issue that we need reliable factoring. However, if someone can review and merge, I can install it in production and hope that gets us back in operation for the frontscope, at least.

fix: Move all calls to cypari into try-except block

---

doc/server-administration.md

In the last update, it was necessary to modify the python environment for the production backscope instance, but there were no commands for that in the server administration doc. This PR adds them.
Moreover, the production Postgres is somehow set up so that SQL_ASCII is the default encoding, leading to #150. This PR provides more flags to the createdb command that overcomes this unusual setup (typically Postgres defaults to Unicode, which is what we want for backscope).
Resolves #150.

doc: Correct command to create database; add python environment commands

---

doc/api_endpoints.md
flaskr/nscope/models.py
flaskr/nscope/test/test_search_oeis.py
flaskr/nscope/views.py

Now that backscope is stable once again, to progress further with the OEIS search bar in the frontscope, it seems prudent to add a search_oeis endpoint to backscope, rather than have the frontscope go directly to the OEIS. That way,
the frontscope is consistently talking only to the backscope, and when/if we convert backscope to have all metadata present on the server by virtue of checking out the git mirror of the OEIS, we can switch to doing the search locally on the server (no need to hit the OEIS) in a seamless fashion from the point of view of the front end.

feat: Add search_oeis endpoint

---

.gitignore
README.md
doc/install-ubuntu.md
flaskr/nscope/test/test_get_oeis_values.py
flaskr/nscope/test/test_search_oeis.py
flaskr/nscope/test/test_wrong_response_type.py
flaskr/nscope/views.py
requirements-freeze.txt
requirements.txt

The branch to be merged uses local sequence file reads as drop-in replacements for OEIS searches.
This change paves the way for code simplifications and reliability improvements. For example, it makes sequences' names and raw references consistently fast to fetch, putting us in a position to fetch them synchronously when a sequence is requested.
This change also makes issue #161 mostly moot. It does this by eliminating the need for OEIS searches from every endpoint except `search_oeis`. The `search_oeis` endpoint is still broken on the branch to be merged, since we don't actually address the search format change.
Before you can test the new code, you'll need to download the OEIS metadata into the right place. You can find instructions for that in the [quick-start …

Store sequence metadata locally

---

doc/server-administration.md

OK, the local metadata version of the server is in production and working from numberscope.colorado.edu frontscope and from my machine. Woohoo. This is just a cleanup of the server admin to reflect the steps I took in installing the new system.

doc: Update server admin to reflect #164
